import {
  Department,
  GovernmentService,
  GovernmentPlatform,
  IntegrationConnection,
  ServiceRequest,
  NotificationItem,
  DataRequirement,
  DataConsent,
  ServiceWorkflow,
  WorkflowStep,
  AuditLog,
  MonitoringSummary
} from '../types';

export const INITIAL_DEPARTMENTS: Department[] = [
  {
    id: 1,
    name: 'Municipal Corporation',
    code: 'MUNICIPAL',
    description: 'Local urban governance, property tax assessments, birth & death registrations, trade licensing, and civic utilities.',
    iconName: 'Building2',
    status: 'ACTIVE',
    servicesCount: 4
  },
  {
    id: 2,
    name: 'Transport Department',
    code: 'TRANSPORT',
    description: 'Vehicle registration, driving license issuance, road permits, fitness certifications, and road safety regulations.',
    iconName: 'Car',
    status: 'ACTIVE',
    servicesCount: 4
  },
  {
    id: 3,
    name: 'Revenue & Land Records',
    code: 'REVENUE',
    description: 'Land ownership records, title mutation, property encumbrance certificates, caste & income certifications, and agricultural land assessments.',
    iconName: 'Landmark',
    status: 'ACTIVE',
    servicesCount: 4
  },
  {
    id: 4,
    name: 'Health & Family Welfare',
    code: 'HEALTH',
    description: 'Public healthcare schemes, health insurance registries, hospital bed allocations, and universal immunization records.',
    iconName: 'HeartPulse',
    status: 'ACTIVE',
    servicesCount: 4
  },
  {
    id: 5,
    name: 'School & Higher Education',
    code: 'EDUCATION',
    description: 'Academic scholarship disbursements, school admissions, certificate verifications, and higher education assistance.',
    iconName: 'GraduationCap',
    status: 'ACTIVE',
    servicesCount: 4
  },
  {
    id: 6,
    name: 'Social Welfare Department',
    code: 'WELFARE',
    description: 'Senior citizen welfare programs, pension assistance, disability support schemes, and financial aid for underserved communities.',
    iconName: 'HandHeart',
    status: 'ACTIVE',
    servicesCount: 4
  },
  {
    id: 7,
    name: 'Agriculture & Farmers Welfare',
    code: 'AGRICULTURE',
    description: 'Direct income support (PM-KISAN), crop insurance settlement (PMFBY), soil health diagnostics, and Kisan Credit Card subventions.',
    iconName: 'Sprout',
    status: 'ACTIVE',
    servicesCount: 4
  },
  {
    id: 8,
    name: 'Food, Civil Supplies & Consumer Affairs',
    code: 'FOOD_SUPPLIES',
    description: 'National food security entitlements (NFSA), One Nation One Ration Card (ONORC), digital smart ration cards, and consumer grievance redressal.',
    iconName: 'ShoppingBag',
    status: 'ACTIVE',
    servicesCount: 4
  },
  {
    id: 9,
    name: 'Labour & Employment',
    code: 'LABOUR',
    description: 'Unorganized sector social security (e-Shram), universal provident fund (EPFO), ESIC healthcare cards, and construction worker welfare grants.',
    iconName: 'HardHat',
    status: 'ACTIVE',
    servicesCount: 4
  },
  {
    id: 10,
    name: 'Finance & Commercial Taxes',
    code: 'FINANCE',
    description: 'Goods & Services Tax (GST) verification, digital e-stamping and non-judicial stamp duty, PM SVANidhi micro-credit, and profession tax.',
    iconName: 'Coins',
    status: 'ACTIVE',
    servicesCount: 4
  },
  {
    id: 11,
    name: 'Women & Child Development',
    code: 'WOMEN_CHILD',
    description: 'Direct maternal nutrition support (PMMVY), Sukanya Samriddhi girl child accounts, Poshan tracker supplementary nutrition, and child protection.',
    iconName: 'Baby',
    status: 'ACTIVE',
    servicesCount: 4
  },
  {
    id: 12,
    name: 'Power & Renewable Energy',
    code: 'POWER',
    description: 'National rooftop solar subsidy (PM Surya Ghar), smart metering, power connection load enhancement, and rural feeder agricultural electrification.',
    iconName: 'Zap',
    status: 'ACTIVE',
    servicesCount: 4
  }
];

export const INITIAL_SERVICES: GovernmentService[] = [
  {
    id: 1,
    name: 'Property Tax Assessment & Receipt',
    code: 'MUN-001',
    description: 'Calculate, view assessment details, pay outstanding property tax dues, and download digitally signed municipal tax receipts.',
    departmentId: 1,
    departmentName: 'Municipal Corporation',
    category: 'MUNICIPAL',
    eligibility: 'Property owners or registered leaseholders in the municipal jurisdiction.',
    requiredDocuments: 'Previous Tax Receipt / Property ID, Registered Sale Deed, Electricity Bill.',
    estimatedProcessingDays: 3,
    fee: 'Free Assessment / Tax as Applicable',
    status: 'ACTIVE',
    isPopular: true
  },
  {
    id: 2,
    name: 'Birth Certificate Issuance',
    code: 'MUN-002',
    description: 'Apply for an official, digitally verifiable birth certificate from the Municipal Registrar of Births and Deaths.',
    departmentId: 1,
    departmentName: 'Municipal Corporation',
    category: 'MUNICIPAL',
    eligibility: 'Parents or legal guardians of individuals born within municipal limits.',
    requiredDocuments: 'Hospital Discharge Summary, Identity Proof of Parents, Address Proof.',
    estimatedProcessingDays: 5,
    fee: '₹ 20',
    status: 'ACTIVE',
    isPopular: true
  },
  {
    id: 3,
    name: 'Trade & Business Operating License',
    code: 'MUN-003',
    description: 'Apply for new commercial trade license or renew existing trade permits within municipal urban jurisdiction.',
    departmentId: 1,
    departmentName: 'Municipal Corporation',
    category: 'MUNICIPAL',
    eligibility: 'Proprietors, partners, or registered companies operating a commercial establishment.',
    requiredDocuments: 'Premises Rent Agreement/Ownership Deed, Business Plan, Fire Safety NOC.',
    estimatedProcessingDays: 7,
    fee: '₹ 250',
    status: 'ACTIVE',
    isPopular: false
  },
  {
    id: 4,
    name: 'Driving Licence Renewal',
    code: 'TRN-001',
    description: 'Renew expired or expiring Driving Licence with contactless biometric and address verification.',
    departmentId: 2,
    departmentName: 'Transport Department',
    category: 'TRANSPORT',
    eligibility: 'Holders of valid Indian Driving Licences within 1 year before or after expiration date.',
    requiredDocuments: 'Existing Driving Licence copy, Medical Certificate (Form 1A if age > 40), Passport photo.',
    estimatedProcessingDays: 4,
    fee: '₹ 200',
    status: 'ACTIVE',
    isPopular: true
  },
  {
    id: 5,
    name: 'Vehicle Ownership Transfer (RC)',
    code: 'TRN-002',
    description: 'Transfer vehicle registration certificate ownership following a sale, inheritance, or auction.',
    departmentId: 2,
    departmentName: 'Transport Department',
    category: 'TRANSPORT',
    eligibility: 'Buyer and seller of a motor vehicle registered in the state.',
    requiredDocuments: 'Form 29 & 30 signed, Original RC Book, Valid Insurance & PUC, Sale Receipt.',
    estimatedProcessingDays: 10,
    fee: '₹ 350',
    status: 'ACTIVE',
    isPopular: true
  },
  {
    id: 6,
    name: 'High Security Registration Plate (HSRP) Request',
    code: 'TRN-003',
    description: 'Book appointment for installation of tamper-proof High Security Registration Plates for registered vehicles.',
    departmentId: 2,
    departmentName: 'Transport Department',
    category: 'TRANSPORT',
    eligibility: 'Registered vehicle owners with standard registration number.',
    requiredDocuments: 'Vehicle RC, Engine & Chassis Number verification.',
    estimatedProcessingDays: 2,
    fee: '₹ 400',
    status: 'ACTIVE',
    isPopular: false
  },
  {
    id: 7,
    name: 'Land Mutation (Namantaran / Record of Rights)',
    code: 'REV-001',
    description: 'Update ownership details in the official state land revenue register following property purchase or inheritance.',
    departmentId: 3,
    departmentName: 'Revenue & Land Records',
    category: 'REVENUE',
    eligibility: 'Legal owners with registered title deed or court succession certificate.',
    requiredDocuments: 'Registered Sale Deed, Previous Khata/Patta copy, Encumbrance Certificate.',
    estimatedProcessingDays: 14,
    fee: '₹ 150',
    status: 'ACTIVE',
    isPopular: true
  },
  {
    id: 8,
    name: 'Income & Asset Certificate',
    code: 'REV-002',
    description: 'Obtain official revenue certified income certificate for educational scholarships, reservations, and welfare subsidies.',
    departmentId: 3,
    departmentName: 'Revenue & Land Records',
    category: 'REVENUE',
    eligibility: 'Permanent state residents requiring income verification for institutional schemes.',
    requiredDocuments: 'Salary Slip / Form 16 / ITR, Bank Statement (6 months), Local Patwari Verification.',
    estimatedProcessingDays: 6,
    fee: '₹ 30',
    status: 'ACTIVE',
    isPopular: true
  },
  {
    id: 9,
    name: 'Community & Caste Certificate',
    code: 'REV-003',
    description: 'Apply for digitally verified Community/Caste Certificate issued by the Tahsildar / Revenue Sub-Divisional Officer.',
    departmentId: 3,
    departmentName: 'Revenue & Land Records',
    category: 'REVENUE',
    eligibility: 'Eligible state residents with historical family lineage records in the taluk.',
    requiredDocuments: 'Parent Caste Certificate, School Leaving Certificate, Proof of Residence.',
    estimatedProcessingDays: 8,
    fee: '₹ 30',
    status: 'ACTIVE',
    isPopular: false
  },
  {
    id: 10,
    name: 'Ayushman Bharat PM-JAY Golden Card',
    code: 'HLT-001',
    description: 'Generate and download Ayushman Bharat digital health card for cashless secondary and tertiary hospitalization.',
    departmentId: 4,
    departmentName: 'Health & Family Welfare',
    category: 'HEALTH',
    eligibility: 'Eligible households under SECC 2011 registry and state health protection criteria.',
    requiredDocuments: 'Aadhaar Card, Ration Card / State Family ID, Mobile Number.',
    estimatedProcessingDays: 1,
    fee: 'Free of Cost',
    status: 'ACTIVE',
    isPopular: true
  },
  {
    id: 11,
    name: 'National & State Post-Matric Scholarship',
    code: 'EDU-001',
    description: 'Financial scholarship assistance for higher secondary, undergraduate, and technical education students.',
    departmentId: 5,
    departmentName: 'School & Higher Education',
    category: 'EDUCATION',
    eligibility: 'Regular students enrolled in recognized state/central institutions with family annual income < ₹ 2.5 Lakhs.',
    requiredDocuments: 'Previous Year Marks Sheet, College Bonafide Certificate, Income Certificate, Bank Passbook.',
    estimatedProcessingDays: 15,
    fee: 'Free of Cost',
    status: 'ACTIVE',
    isPopular: true
  },
  {
    id: 12,
    name: 'Old Age & Senior Citizen Pension Scheme',
    code: 'WEL-001',
    description: 'Monthly financial pension support for senior citizens living without organized pension benefits.',
    departmentId: 6,
    departmentName: 'Social Welfare Department',
    category: 'WELFARE',
    eligibility: 'Senior citizens aged 60 years and above belonging to BPL or low-income threshold.',
    requiredDocuments: 'Age Proof (Birth Certificate/Voter ID), BPL Card, Bank Account Details (Aadhaar linked).',
    estimatedProcessingDays: 12,
    fee: 'Free of Cost',
    status: 'ACTIVE',
    isPopular: true
  },
  {
    id: 13,
    name: 'Water Supply & Sewerage Connection NOC',
    code: 'MUN-004',
    description: 'Apply for fresh municipal piped water connection or sewerage pipeline sanction with automated cadastral verification.',
    departmentId: 1,
    departmentName: 'Municipal Corporation',
    category: 'MUNICIPAL',
    eligibility: 'Registered property owners with cleared municipal property tax records.',
    requiredDocuments: 'Property Tax Clearance, Building Sanction Plan, Identity Proof.',
    estimatedProcessingDays: 5,
    fee: '₹ 150',
    status: 'ACTIVE',
    isPopular: false
  },
  {
    id: 14,
    name: 'Commercial Vehicle Fitness & Inspection Certificate',
    code: 'TRN-004',
    description: 'Statutory roadworthiness inspection and digital automated green fitness certificate for commercial transport.',
    departmentId: 2,
    departmentName: 'Transport Department',
    category: 'TRANSPORT',
    eligibility: 'Commercial transport and heavy passenger vehicle operators.',
    requiredDocuments: 'Vehicle RC, Pollution Certificate (PUC), Speed Governor Certificate, Tax Token.',
    estimatedProcessingDays: 2,
    fee: '₹ 600',
    status: 'ACTIVE',
    isPopular: false
  },
  {
    id: 15,
    name: 'Non-Encumbrance Title Certificate (EC)',
    code: 'REV-004',
    description: 'Search and obtain digitally signed 30-year property transaction history and non-encumbrance certificate.',
    departmentId: 3,
    departmentName: 'Revenue & Land Records',
    category: 'REVENUE',
    eligibility: 'Property owners, purchasers, or financial institutions seeking title clarity.',
    requiredDocuments: 'Survey Number, Khata/Patta Details, Previous Sale Deed Copy.',
    estimatedProcessingDays: 3,
    fee: '₹ 100',
    status: 'ACTIVE',
    isPopular: true
  },
  {
    id: 16,
    name: 'Ayushman Bharat Health Account (ABHA ID)',
    code: 'HLT-002',
    description: 'Create a 14-digit ABHA digital health account to securely access and share health records across hospitals nationwide.',
    departmentId: 4,
    departmentName: 'Health & Family Welfare',
    category: 'HEALTH',
    eligibility: 'Any Indian citizen possessing an active Aadhaar number or Mobile ID.',
    requiredDocuments: 'Aadhaar Card OTP Verification, Mobile Number.',
    estimatedProcessingDays: 1,
    fee: 'Free of Cost',
    status: 'ACTIVE',
    isPopular: true
  },
  {
    id: 17,
    name: 'Universal Child & Mother Immunization Record',
    code: 'HLT-003',
    description: 'Access digital immunization passport and schedule upcoming national immunization drives (U-WIN Portal integration).',
    departmentId: 4,
    departmentName: 'Health & Family Welfare',
    category: 'HEALTH',
    eligibility: 'Pregnant women and children aged 0 to 6 years residing in India.',
    requiredDocuments: 'Mother/Guardian Aadhaar, Hospital Birth Summary.',
    estimatedProcessingDays: 1,
    fee: 'Free of Cost',
    status: 'ACTIVE',
    isPopular: false
  },
  {
    id: 18,
    name: 'Digital Academic Credential Verification (NAD / APAAR)',
    code: 'EDU-002',
    description: 'Verify degree diplomas, marksheets, and university transcripts instantly via the National Academic Depository.',
    departmentId: 5,
    departmentName: 'School & Higher Education',
    category: 'EDUCATION',
    eligibility: 'Students, alumni, employers, and verifying academic institutions.',
    requiredDocuments: 'APAAR / ABC ID, Roll Number, Year of Passing.',
    estimatedProcessingDays: 1,
    fee: 'Free of Cost',
    status: 'ACTIVE',
    isPopular: false
  },
  {
    id: 19,
    name: 'Right to Education (RTE 25%) EWS School Admission',
    code: 'EDU-003',
    description: 'Online lottery and admission allotment for economically disadvantaged children in private unaided schools under Section 12(1)(c).',
    departmentId: 5,
    departmentName: 'School & Higher Education',
    category: 'EDUCATION',
    eligibility: 'Children entering nursery/Class 1 whose family annual income meets state EWS criteria.',
    requiredDocuments: 'Income Certificate, Birth Certificate, Address Proof.',
    estimatedProcessingDays: 10,
    fee: 'Free of Cost',
    status: 'ACTIVE',
    isPopular: true
  },
  {
    id: 20,
    name: 'Widow & Destitute Women Pension Support',
    code: 'WEL-002',
    description: 'Monthly DBT pension assistance to widowed, separated, or abandoned women to ensure economic dignity.',
    departmentId: 6,
    departmentName: 'Social Welfare Department',
    category: 'WELFARE',
    eligibility: 'Widowed women aged 18+ residing in the state with annual family income below poverty ceiling.',
    requiredDocuments: 'Death Certificate of Husband, Income Certificate, Bank Account Details, Aadhaar.',
    estimatedProcessingDays: 10,
    fee: 'Free of Cost',
    status: 'ACTIVE',
    isPopular: false
  },
  {
    id: 21,
    name: 'Divyangjan Disability Monthly Subsistence Allowance',
    code: 'WEL-003',
    description: 'Direct financial assistance and assistive equipment subsidy for persons with benchmark disabilities (40%+).',
    departmentId: 6,
    departmentName: 'Social Welfare Department',
    category: 'WELFARE',
    eligibility: 'Persons with verified UDID card with disability assessed at 40% or higher.',
    requiredDocuments: 'UDID Card, Disability Medical Certificate, Aadhaar, Bank Passbook.',
    estimatedProcessingDays: 8,
    fee: 'Free of Cost',
    status: 'ACTIVE',
    isPopular: false
  },
  {
    id: 22,
    name: 'PM-KISAN Samman Nidhi e-KYC & Direct Benefit Transfer',
    code: 'AGR-001',
    description: 'Register for ₹ 6,000 annual income support transferred directly to bank account in three 4-monthly installments.',
    departmentId: 7,
    departmentName: 'Agriculture & Farmers Welfare',
    category: 'AGRICULTURE',
    eligibility: 'Small and marginal landholder farmer families with cultivable land in state revenue records.',
    requiredDocuments: 'Aadhaar Card, Land Record RoR (Khata/Khasra), Aadhaar-linked Bank Account.',
    estimatedProcessingDays: 7,
    fee: 'Free of Cost',
    status: 'ACTIVE',
    isPopular: true
  },
  {
    id: 23,
    name: 'Pradhan Mantri Fasal Bima Yojana (Crop Insurance Claim)',
    code: 'AGR-002',
    description: 'Submit yield loss notices, track automated satellite crop health verification, and receive claim settlements.',
    departmentId: 7,
    departmentName: 'Agriculture & Farmers Welfare',
    category: 'AGRICULTURE',
    eligibility: 'Farmers (loanee and non-loanee) growing notified crops in designated areas.',
    requiredDocuments: 'Sowing Certificate, Land RoR, Bank Account Passbook, Aadhaar.',
    estimatedProcessingDays: 14,
    fee: 'Nominal Premium (1.5% to 2%)',
    status: 'ACTIVE',
    isPopular: true
  },
  {
    id: 24,
    name: 'Soil Health Diagnostic Card & Nutrient Advisory',
    code: 'AGR-003',
    description: 'Order GPS-tagged soil chemical analysis and receive customized organic and chemical fertilizer advisory.',
    departmentId: 7,
    departmentName: 'Agriculture & Farmers Welfare',
    category: 'AGRICULTURE',
    eligibility: 'All cultivating farmers with registered cadastral land holdings.',
    requiredDocuments: 'Farmer ID / Aadhaar, Land Survey Number.',
    estimatedProcessingDays: 6,
    fee: 'Free of Cost',
    status: 'ACTIVE',
    isPopular: false
  },
  {
    id: 25,
    name: 'One Nation One Ration Card (ONORC) National Portability',
    code: 'FCS-001',
    description: 'Avail subsidized food grains from any Fair Price Shop (FPS) across India using biometric Aadhaar authentication.',
    departmentId: 8,
    departmentName: 'Food, Civil Supplies & Consumer Affairs',
    category: 'FOOD_SUPPLIES',
    eligibility: 'All NFSA / Antyodaya Anna Yojana (AAY) ration cardholders migrating across state borders.',
    requiredDocuments: 'Existing Ration Card Number, Aadhaar Number of Beneficiary.',
    estimatedProcessingDays: 1,
    fee: 'Free of Cost',
    status: 'ACTIVE',
    isPopular: true
  },
  {
    id: 26,
    name: 'New Digital Smart Ration Card & Member Addition',
    code: 'FCS-002',
    description: 'Apply for new family digital ration card, modify family member roster, or update residential jurisdiction.',
    departmentId: 8,
    departmentName: 'Food, Civil Supplies & Consumer Affairs',
    category: 'FOOD_SUPPLIES',
    eligibility: 'Families residing in state without existing active ration card in any state.',
    requiredDocuments: 'Family Aadhaar Cards, Address Proof, Income Certificate / Gas Connection Number.',
    estimatedProcessingDays: 12,
    fee: '₹ 25',
    status: 'ACTIVE',
    isPopular: true
  },
  {
    id: 27,
    name: 'Fair Price Shop (FPS) Monthly Entitlement Tracker',
    code: 'FCS-003',
    description: 'Check real-time stock availability, monthly foodgrain entitlement quota, and transaction receipts.',
    departmentId: 8,
    departmentName: 'Food, Civil Supplies & Consumer Affairs',
    category: 'FOOD_SUPPLIES',
    eligibility: 'Registered NFSA and Priority Household beneficiaries.',
    requiredDocuments: 'Ration Card Number / Linked Mobile Number.',
    estimatedProcessingDays: 1,
    fee: 'Free of Cost',
    status: 'ACTIVE',
    isPopular: false
  },
  {
    id: 28,
    name: 'e-Shram National Database Unorganized Worker Smart Card',
    code: 'LBR-001',
    description: 'Register in the National Database of Unorganized Workers (NDUW) to receive a 12-digit UAN and ₹2 Lakh accident cover.',
    departmentId: 9,
    departmentName: 'Labour & Employment',
    category: 'LABOUR',
    eligibility: 'Unorganized workers aged 16 to 59 years not enrolled in EPFO or ESIC.',
    requiredDocuments: 'Aadhaar Card, Mobile Number linked with Aadhaar, Bank Account Details.',
    estimatedProcessingDays: 1,
    fee: 'Free of Cost',
    status: 'ACTIVE',
    isPopular: true
  },
  {
    id: 29,
    name: 'EPFO Universal Account Number (UAN) Transfer & Settlement',
    code: 'LBR-002',
    description: 'Consolidate multiple provident fund accounts, submit Form 19/10C online, and track EPF claim settlement in 72 hours.',
    departmentId: 9,
    departmentName: 'Labour & Employment',
    category: 'LABOUR',
    eligibility: 'Formal sector employees enrolled under Employees’ Provident Fund Organisation.',
    requiredDocuments: 'Active UAN, Aadhaar, Verified Bank Account with IFSC.',
    estimatedProcessingDays: 3,
    fee: 'Free of Cost',
    status: 'ACTIVE',
    isPopular: true
  },
  {
    id: 30,
    name: 'Building & Other Construction Workers (BOCW) Welfare Grant',
    code: 'LBR-003',
    description: 'Access educational stipends, maternity assistance, tool grants, and healthcare benefits for construction laborers.',
    departmentId: 9,
    departmentName: 'Labour & Employment',
    category: 'LABOUR',
    eligibility: 'Workers engaged in building or construction work for not less than 90 days in the preceding 12 months.',
    requiredDocuments: 'Employer Work Certificate, Aadhaar, Bank Details, Age Proof.',
    estimatedProcessingDays: 10,
    fee: '₹ 20',
    status: 'ACTIVE',
    isPopular: false
  },
  {
    id: 31,
    name: 'Goods & Services Tax (GST) Verification & Taxpayer Certificate',
    code: 'FIN-001',
    description: 'Instant lookup and cryptographic verification of GSTIN registration, compliance filing history, and active legal status.',
    departmentId: 10,
    departmentName: 'Finance & Commercial Taxes',
    category: 'FINANCE',
    eligibility: 'Businesses, consumers, and vendors seeking GST validation.',
    requiredDocuments: '15-digit GSTIN Identifier or PAN Number.',
    estimatedProcessingDays: 1,
    fee: 'Free of Cost',
    status: 'ACTIVE',
    isPopular: true
  },
  {
    id: 32,
    name: 'Digital e-Stamping & Non-Judicial Stamp Duty e-Challan',
    code: 'FIN-002',
    description: 'Generate legally valid, tamper-proof electronic stamp paper for agreements, affidavits, and real estate conveyance deeds.',
    departmentId: 10,
    departmentName: 'Finance & Commercial Taxes',
    category: 'FINANCE',
    eligibility: 'Any individual or corporate entity executing a legal document requiring stamp duty.',
    requiredDocuments: 'First Party and Second Party Names, Purpose of Stamp Paper, PAN/Aadhaar.',
    estimatedProcessingDays: 1,
    fee: 'Stamp Duty as per State Stamp Act',
    status: 'ACTIVE',
    isPopular: false
  },
  {
    id: 33,
    name: 'PM SVANidhi Micro-Credit Facility for Urban Vendors',
    code: 'FIN-003',
    description: 'Apply for collateral-free working capital loan up to ₹ 50,000 with 7% interest subsidy for urban street vendors.',
    departmentId: 10,
    departmentName: 'Finance & Commercial Taxes',
    category: 'FINANCE',
    eligibility: 'Urban street vendors with Certificate of Vending or ULB recommendation letter.',
    requiredDocuments: 'Vending Certificate / Urban ID, Aadhaar Card, Bank Account.',
    estimatedProcessingDays: 5,
    fee: 'Free of Cost',
    status: 'ACTIVE',
    isPopular: true
  },
  {
    id: 34,
    name: 'Pradhan Mantri Matru Vandana Yojana (PMMVY) Maternity Benefit',
    code: 'WCD-001',
    description: 'Conditional cash transfer of ₹ 5,000 directly to pregnant and lactating mothers for health, nutrition, and wage loss.',
    departmentId: 11,
    departmentName: 'Women & Child Development',
    category: 'WOMEN_CHILD',
    eligibility: 'Pregnant women and lactating mothers for the first living child belonging to economically eligible households.',
    requiredDocuments: 'Mother and Child Protection (MCP) Card, Aadhaar Card of Mother, Bank Passbook.',
    estimatedProcessingDays: 10,
    fee: 'Free of Cost',
    status: 'ACTIVE',
    isPopular: true
  },
  {
    id: 35,
    name: 'Sukanya Samriddhi Girl Child Institutional Savings Integration',
    code: 'WCD-002',
    description: 'Link and monitor high-yield government savings account for girl children up to age 10 with sovereign interest guarantees.',
    departmentId: 11,
    departmentName: 'Women & Child Development',
    category: 'WOMEN_CHILD',
    eligibility: 'Parents or legal guardians of a girl child below 10 years of age.',
    requiredDocuments: 'Birth Certificate of Girl Child, Guardian Identity & Address Proof, Aadhaar.',
    estimatedProcessingDays: 4,
    fee: 'Initial Deposit ₹ 250',
    status: 'ACTIVE',
    isPopular: true
  },
  {
    id: 36,
    name: 'PM Surya Ghar Muft Bijli Yojana (Rooftop Solar Subsidy)',
    code: 'PWR-001',
    description: 'Apply for central financial assistance up to ₹ 78,000 for installing residential rooftop solar panels and net metering.',
    departmentId: 12,
    departmentName: 'Power & Renewable Energy',
    category: 'POWER',
    eligibility: 'Residential households with valid electricity consumer number and roof ownership.',
    requiredDocuments: 'Electricity Bill (last 3 months), Rooftop Area Details, Aadhaar, Bank Details.',
    estimatedProcessingDays: 7,
    fee: 'Free Application / Subsidy Direct to Bank',
    status: 'ACTIVE',
    isPopular: true
  },
  {
    id: 37,
    name: 'Domestic Electricity Connection Load Enhancement & Meter Transfer',
    code: 'PWR-002',
    description: 'Request sanctioned load upgrade or name transfer on existing power utility accounts without visiting DISCOM sub-stations.',
    departmentId: 12,
    departmentName: 'Power & Renewable Energy',
    category: 'POWER',
    eligibility: 'Registered power consumers with no pending power theft or surcharge disputes.',
    requiredDocuments: 'Latest Electricity Bill, Ownership Proof / Registered Lease, Aadhaar.',
    estimatedProcessingDays: 3,
    fee: 'Standard DISCOM Security Deposit as per Tariff',
    status: 'ACTIVE',
    isPopular: false
  },
  {
    id: 38,
    name: 'PM KUSUM Agricultural Solar Pump Energization Scheme',
    code: 'PWR-003',
    description: 'Government capital subsidy of up to 60% for farmers to install standalone solar water pumps for farm irrigation.',
    departmentId: 12,
    departmentName: 'Power & Renewable Energy',
    category: 'POWER',
    eligibility: 'Farmers, farmer producer organizations (FPOs), and water user associations.',
    requiredDocuments: 'Land Revenue RoR, Bank Passbook, Aadhaar, Irrigation Source Certificate.',
    estimatedProcessingDays: 14,
    fee: 'Farmer share 10% - 40%',
    status: 'ACTIVE',
    isPopular: false
  }
];

export const INITIAL_PLATFORMS: GovernmentPlatform[] = [
  {
    id: 1,
    name: 'e-NagarPalika Municipal Core',
    code: 'EPALIKA-CORE',
    departmentId: 1,
    departmentName: 'Municipal Corporation',
    description: 'Central municipal administration and civic tax assessment microservice cluster.',
    platformType: 'GOVERNMENT_DATABASE',
    environment: 'PRODUCTION',
    connectionStatus: 'CONNECTED',
    integrationStatus: 'READY',
    endpointUrl: 'https://epalika.gov.in/api/v2',
    authProtocol: 'OAUTH2_MGS',
    uptimePercentage: 99.9,
    lastPingAt: 'Just now',
    createdAt: new Date().toISOString()
  },
  {
    id: 2,
    name: 'VAHAN 4.0 Vehicle Registry',
    code: 'VAHAN-REG-4',
    departmentId: 2,
    departmentName: 'Transport Department',
    description: 'National vehicle registry, ownership records, and state border taxation engine.',
    platformType: 'API_PLATFORM',
    environment: 'PRODUCTION',
    connectionStatus: 'CONNECTED',
    integrationStatus: 'READY',
    endpointUrl: 'https://vahan.parivahan.gov.in/api/v4',
    authProtocol: 'PKI_X509',
    uptimePercentage: 99.8,
    lastPingAt: '1 min ago',
    createdAt: new Date().toISOString()
  },
  {
    id: 3,
    name: 'SARATHI 4.0 Driving License System',
    code: 'SARATHI-DL-4',
    departmentId: 2,
    departmentName: 'Transport Department',
    description: 'Licensing authority workflow, biometric deduplication, and automated driving test records.',
    platformType: 'API_PLATFORM',
    environment: 'PRODUCTION',
    connectionStatus: 'CONNECTED',
    integrationStatus: 'READY',
    endpointUrl: 'https://sarathi.parivahan.gov.in/api/v4',
    authProtocol: 'PKI_X509',
    uptimePercentage: 99.7,
    lastPingAt: 'Just now',
    createdAt: new Date().toISOString()
  },
  {
    id: 4,
    name: 'Bhoomi Land Records Information System',
    code: 'BHOOMI-LRS',
    departmentId: 3,
    departmentName: 'Revenue & Land Records',
    description: 'Spatial cadastral maps, RoR ownership database, and sub-registrar deed indexing.',
    platformType: 'GOVERNMENT_DATABASE',
    environment: 'PRODUCTION',
    connectionStatus: 'CONNECTED',
    integrationStatus: 'READY',
    endpointUrl: 'https://bhoomi.revenue.gov.in/api/v3',
    authProtocol: 'SAML2_GOV',
    uptimePercentage: 99.9,
    lastPingAt: '3 mins ago',
    createdAt: new Date().toISOString()
  },
  {
    id: 5,
    name: 'Ayushman Bharat PM-JAY National Portal',
    code: 'PMJAY-NAT',
    departmentId: 4,
    departmentName: 'Health & Family Welfare',
    description: 'Beneficiary Identification System (BIS) and Hospital Empanelment Management System.',
    platformType: 'CITIZEN_PORTAL',
    environment: 'PRODUCTION',
    connectionStatus: 'CONNECTED',
    integrationStatus: 'READY',
    endpointUrl: 'https://pmjay.gov.in/api/v2',
    authProtocol: 'OAUTH2_MGS',
    uptimePercentage: 99.9,
    lastPingAt: 'Just now',
    createdAt: new Date().toISOString()
  },
  {
    id: 6,
    name: 'DigiLocker Government Document Exchange',
    code: 'DIGILOCKER-GW',
    departmentId: 3,
    departmentName: 'Inter-Department Gateway',
    description: 'Secure sovereign repository for digitally signed citizen credentials and certificates.',
    platformType: 'API_PLATFORM',
    environment: 'PRODUCTION',
    connectionStatus: 'CONNECTED',
    integrationStatus: 'READY',
    endpointUrl: 'https://digilocker.gov.in/interop/v1',
    authProtocol: 'OAUTH2_MGS',
    uptimePercentage: 100.0,
    lastPingAt: 'Just now',
    createdAt: new Date().toISOString()
  },
  {
    id: 7,
    name: 'National Scholarship & PFMS Portal',
    code: 'PFMS-NSP',
    departmentId: 5,
    departmentName: 'School & Higher Education',
    description: 'Central direct benefit transfer disbursement gateway for student scholarships.',
    platformType: 'API_PLATFORM',
    environment: 'PRODUCTION',
    connectionStatus: 'CONNECTED',
    integrationStatus: 'READY',
    endpointUrl: 'https://scholarships.gov.in/api/v1',
    authProtocol: 'PKI_X509',
    uptimePercentage: 99.6,
    lastPingAt: '4 mins ago',
    createdAt: new Date().toISOString()
  },
  {
    id: 8,
    name: 'Social Welfare Beneficiary DB',
    code: 'SW-BENEFICIARY',
    departmentId: 6,
    departmentName: 'Social Welfare Department',
    description: 'State-wide registry of pension beneficiaries and disability welfare grants.',
    platformType: 'GOVERNMENT_DATABASE',
    environment: 'PRODUCTION',
    connectionStatus: 'CONNECTED',
    integrationStatus: 'READY',
    endpointUrl: 'https://welfare.gov.in/api/v2',
    authProtocol: 'SAML2_GOV',
    uptimePercentage: 99.8,
    lastPingAt: '2 mins ago',
    createdAt: new Date().toISOString()
  },
  {
    id: 9,
    name: 'PM-KISAN & AgriStack Digital Repository',
    code: 'AGRI-KISAN-PORTAL',
    departmentId: 7,
    departmentName: 'Agriculture & Farmers Welfare',
    description: 'Direct income support, digital land parcel identification (FARMS ID), and crop registry integration.',
    platformType: 'API_PLATFORM',
    environment: 'PRODUCTION',
    connectionStatus: 'CONNECTED',
    integrationStatus: 'READY',
    endpointUrl: 'https://pmkisan.gov.in/api/v4',
    authProtocol: 'PKI_X509',
    uptimePercentage: 99.9,
    lastPingAt: 'Just now',
    createdAt: new Date().toISOString()
  },
  {
    id: 10,
    name: 'Annavitran & ONORC Food Security Cloud',
    code: 'NFSA-ONORC-GW',
    departmentId: 8,
    departmentName: 'Food, Civil Supplies & Consumer Affairs',
    description: 'National food grain entitlement distribution, biometric ration card portability, and Fair Price Shop telemetry.',
    platformType: 'GOVERNMENT_DATABASE',
    environment: 'PRODUCTION',
    connectionStatus: 'CONNECTED',
    integrationStatus: 'READY',
    endpointUrl: 'https://annavitran.nic.in/api/v2',
    authProtocol: 'SAML2_GOV',
    uptimePercentage: 99.8,
    lastPingAt: '1 min ago',
    createdAt: new Date().toISOString()
  },
  {
    id: 11,
    name: 'e-Shram & EPFO National Labor Gateway',
    code: 'ESHRAM-EPFO-GW',
    departmentId: 9,
    departmentName: 'Labour & Employment',
    description: 'Universal account verification, unorganized workforce social registry, and ESIC healthcare entitlement bridge.',
    platformType: 'API_PLATFORM',
    environment: 'PRODUCTION',
    connectionStatus: 'CONNECTED',
    integrationStatus: 'READY',
    endpointUrl: 'https://eshram.gov.in/api/v3',
    authProtocol: 'PKI_X509',
    uptimePercentage: 99.9,
    lastPingAt: 'Just now',
    createdAt: new Date().toISOString()
  },
  {
    id: 12,
    name: 'GSTN & Digital e-Stamping Interoperability Engine',
    code: 'GSTN-STAMP-HUB',
    departmentId: 10,
    departmentName: 'Finance & Commercial Taxes',
    description: 'Goods and Services Tax network validation, electronic non-judicial stamp duty, and commercial invoice verification.',
    platformType: 'API_PLATFORM',
    environment: 'PRODUCTION',
    connectionStatus: 'CONNECTED',
    integrationStatus: 'READY',
    endpointUrl: 'https://services.gst.gov.in/api/v1',
    authProtocol: 'PKI_X509',
    uptimePercentage: 100.0,
    lastPingAt: 'Just now',
    createdAt: new Date().toISOString()
  },
  {
    id: 13,
    name: 'Poshan Tracker & PMMVY Direct Benefit Platform',
    code: 'POSHAN-PMMVY-REG',
    departmentId: 11,
    departmentName: 'Women & Child Development',
    description: 'Maternal health benefit distribution, child nutrition tracking, and Sukanya Samriddhi girl child enrollment bridge.',
    platformType: 'CITIZEN_PORTAL',
    environment: 'PRODUCTION',
    connectionStatus: 'CONNECTED',
    integrationStatus: 'READY',
    endpointUrl: 'https://poshantracker.in/api/v2',
    authProtocol: 'OAUTH2_MGS',
    uptimePercentage: 99.7,
    lastPingAt: '2 mins ago',
    createdAt: new Date().toISOString()
  },
  {
    id: 14,
    name: 'PM Surya Ghar National Rooftop Solar Grid Portal',
    code: 'SURYAGHAR-GRID',
    departmentId: 12,
    departmentName: 'Power & Renewable Energy',
    description: 'DISCOM net metering approval, national renewable energy feeder telemetry, and direct subsidy credit gateway.',
    platformType: 'API_PLATFORM',
    environment: 'PRODUCTION',
    connectionStatus: 'CONNECTED',
    integrationStatus: 'READY',
    endpointUrl: 'https://pmsuryaghar.gov.in/api/v1',
    authProtocol: 'PKI_X509',
    uptimePercentage: 99.9,
    lastPingAt: 'Just now',
    createdAt: new Date().toISOString()
  }
];

export const INITIAL_CONNECTIONS: IntegrationConnection[] = [
  {
    id: 1,
    name: 'Municipal-to-Land Records Pipe',
    sourcePlatformId: 1,
    sourcePlatformName: 'e-NagarPalika Municipal Core',
    sourceDepartmentId: 1,
    sourceDepartmentName: 'Municipal Corporation',
    destinationPlatformId: 4,
    destinationPlatformName: 'Bhoomi Land Records Information System',
    destinationDepartmentId: 3,
    destinationDepartmentName: 'Revenue & Land Records',
    serviceId: 1,
    serviceName: 'Property Tax Assessment & Receipt',
    purpose: 'Real-time Property Deed Verification',
    connectionType: 'SECURE_GATEWAY',
    status: 'ACTIVE',
    dataExchangeProtocol: 'HTTPS/JSON (e-Gov Interop v2.1)',
    dataCategories: 'Property Records, Cadastral Map ID',
    consentRequired: true,
    totalTransactionsProcessed: 142050,
    lastTestedAt: new Date().toISOString(),
    createdAt: new Date().toISOString()
  },
  {
    id: 2,
    name: 'VAHAN to DigiLocker Sync',
    sourcePlatformId: 2,
    sourcePlatformName: 'VAHAN 4.0 Vehicle Registry',
    sourceDepartmentId: 2,
    sourceDepartmentName: 'Transport Department',
    destinationPlatformId: 6,
    destinationPlatformName: 'DigiLocker Government Document Exchange',
    destinationDepartmentId: 3,
    destinationDepartmentName: 'Inter-Department Gateway',
    serviceId: 5,
    serviceName: 'Vehicle Ownership Transfer (RC)',
    purpose: 'Digital Vehicle RC Issuance',
    connectionType: 'REST_API',
    status: 'ACTIVE',
    dataExchangeProtocol: 'HTTPS/JSON (e-Gov Interop v2.1)',
    dataCategories: 'Vehicle RC, PUC Certificate',
    consentRequired: true,
    totalTransactionsProcessed: 584200,
    lastTestedAt: new Date().toISOString(),
    createdAt: new Date().toISOString()
  },
  {
    id: 3,
    name: 'SARATHI Biometric Verification',
    sourcePlatformId: 3,
    sourcePlatformName: 'SARATHI 4.0 Driving License System',
    sourceDepartmentId: 2,
    sourceDepartmentName: 'Transport Department',
    destinationPlatformId: 6,
    destinationPlatformName: 'DigiLocker Government Document Exchange',
    destinationDepartmentId: 3,
    destinationDepartmentName: 'Inter-Department Gateway',
    serviceId: 4,
    serviceName: 'Driving Licence Renewal',
    purpose: 'Driving Licence Credential Verification',
    connectionType: 'REST_API',
    status: 'ACTIVE',
    dataExchangeProtocol: 'HTTPS/JSON (e-Gov Interop v2.1)',
    dataCategories: 'Driving Licence, Biometric Hash',
    consentRequired: true,
    totalTransactionsProcessed: 398100,
    lastTestedAt: new Date().toISOString(),
    createdAt: new Date().toISOString()
  },
  {
    id: 4,
    name: 'Bhoomi Encumbrance Gateway',
    sourcePlatformId: 4,
    sourcePlatformName: 'Bhoomi Land Records Information System',
    sourceDepartmentId: 3,
    sourceDepartmentName: 'Revenue & Land Records',
    destinationPlatformId: 6,
    destinationPlatformName: 'DigiLocker Government Document Exchange',
    destinationDepartmentId: 3,
    destinationDepartmentName: 'Inter-Department Gateway',
    serviceId: 7,
    serviceName: 'Land Mutation (Namantaran / Record of Rights)',
    purpose: 'Land Title RoR Certificate Delivery',
    connectionType: 'DATA_PIPELINE',
    status: 'ACTIVE',
    dataExchangeProtocol: 'HTTPS/JSON (e-Gov Interop v2.1)',
    dataCategories: 'Record of Rights, Mutation Order',
    consentRequired: true,
    totalTransactionsProcessed: 276900,
    lastTestedAt: new Date().toISOString(),
    createdAt: new Date().toISOString()
  },
  {
    id: 5,
    name: 'Ayushman BIS Direct Check',
    sourcePlatformId: 5,
    sourcePlatformName: 'Ayushman Bharat PM-JAY National Portal',
    sourceDepartmentId: 4,
    sourceDepartmentName: 'Health & Family Welfare',
    destinationPlatformId: 6,
    destinationPlatformName: 'DigiLocker Government Document Exchange',
    destinationDepartmentId: 3,
    destinationDepartmentName: 'Inter-Department Gateway',
    serviceId: 10,
    serviceName: 'Ayushman Bharat PM-JAY Golden Card',
    purpose: 'Golden Card Verification',
    connectionType: 'REST_API',
    status: 'ACTIVE',
    dataExchangeProtocol: 'HTTPS/JSON (e-Gov Interop v2.1)',
    dataCategories: 'Health Card ID, SECC Ration Record',
    consentRequired: true,
    totalTransactionsProcessed: 189000,
    lastTestedAt: new Date().toISOString(),
    createdAt: new Date().toISOString()
  },
  {
    id: 6,
    name: 'PFMS Education Scholarship Pipe',
    sourcePlatformId: 7,
    sourcePlatformName: 'National Scholarship & PFMS Portal',
    sourceDepartmentId: 5,
    sourceDepartmentName: 'School & Higher Education',
    destinationPlatformId: 6,
    destinationPlatformName: 'DigiLocker Government Document Exchange',
    destinationDepartmentId: 3,
    destinationDepartmentName: 'Inter-Department Gateway',
    serviceId: 11,
    serviceName: 'National & State Post-Matric Scholarship',
    purpose: 'Student Academic Marks Verification',
    connectionType: 'REST_API',
    status: 'APPROVED',
    dataExchangeProtocol: 'HTTPS/JSON (e-Gov Interop v2.1)',
    dataCategories: 'Marks Card, College Bonafide',
    consentRequired: true,
    totalTransactionsProcessed: 74300,
    lastTestedAt: new Date().toISOString(),
    createdAt: new Date().toISOString()
  },
  {
    id: 7,
    name: 'Municipal Trade to Safety Gateway',
    sourcePlatformId: 1,
    sourcePlatformName: 'e-NagarPalika Municipal Core',
    sourceDepartmentId: 1,
    sourceDepartmentName: 'Municipal Corporation',
    destinationPlatformId: 8,
    destinationPlatformName: 'Social Welfare Beneficiary DB',
    destinationDepartmentId: 6,
    destinationDepartmentName: 'Social Welfare Department',
    serviceId: 3,
    serviceName: 'Trade & Business Operating License',
    purpose: 'Commercial Safety Clearance',
    connectionType: 'SECURE_GATEWAY',
    status: 'UNDER_REVIEW',
    dataExchangeProtocol: 'HTTPS/JSON (e-Gov Interop v2.1)',
    dataCategories: 'Safety NOC, Operating Premise ID',
    consentRequired: true,
    totalTransactionsProcessed: 0,
    lastTestedAt: new Date().toISOString(),
    createdAt: new Date().toISOString()
  },
  {
    id: 8,
    name: 'Welfare Pension Direct Bank Transfer',
    sourcePlatformId: 8,
    sourcePlatformName: 'Social Welfare Beneficiary DB',
    sourceDepartmentId: 6,
    sourceDepartmentName: 'Social Welfare Department',
    destinationPlatformId: 7,
    destinationPlatformName: 'National Scholarship & PFMS Portal',
    destinationDepartmentId: 5,
    destinationDepartmentName: 'School & Higher Education',
    serviceId: 12,
    serviceName: 'Old Age & Senior Citizen Pension Scheme',
    purpose: 'Direct Benefit Transfer Routing',
    connectionType: 'DATA_PIPELINE',
    status: 'DRAFT',
    dataExchangeProtocol: 'HTTPS/JSON (e-Gov Interop v2.1)',
    dataCategories: 'Aadhaar Payment Bridge, Bank Account',
    consentRequired: true,
    totalTransactionsProcessed: 0,
    lastTestedAt: new Date().toISOString(),
    createdAt: new Date().toISOString()
  },
  {
    id: 9,
    name: 'PM-KISAN to Bhoomi LRS Cadastral Sync',
    sourcePlatformId: 9,
    sourcePlatformName: 'PM-KISAN & AgriStack Digital Repository',
    sourceDepartmentId: 7,
    sourceDepartmentName: 'Agriculture & Farmers Welfare',
    destinationPlatformId: 4,
    destinationPlatformName: 'Bhoomi Land Records Information System',
    destinationDepartmentId: 3,
    destinationDepartmentName: 'Revenue & Land Records',
    serviceId: 22,
    serviceName: 'PM-KISAN Samman Nidhi Direct Support',
    purpose: 'Farmland Title & Landholding Verification',
    connectionType: 'SECURE_GATEWAY',
    status: 'ACTIVE',
    dataExchangeProtocol: 'HTTPS/JSON (e-Gov Interop v2.1)',
    dataCategories: 'FARMS ID, Land Parcel Khata, Survey Number',
    consentRequired: true,
    totalTransactionsProcessed: 324180,
    lastTestedAt: new Date().toISOString(),
    createdAt: new Date().toISOString()
  },
  {
    id: 10,
    name: 'ONORC to DigiLocker Ration Entitlement Sync',
    sourcePlatformId: 10,
    sourcePlatformName: 'Annavitran & ONORC Food Security Cloud',
    sourceDepartmentId: 8,
    sourceDepartmentName: 'Food, Civil Supplies & Consumer Affairs',
    destinationPlatformId: 6,
    destinationPlatformName: 'DigiLocker Government Document Exchange',
    destinationDepartmentId: 3,
    destinationDepartmentName: 'Inter-Department Gateway',
    serviceId: 26,
    serviceName: 'New Digital Smart Ration Card & Member Addition',
    purpose: 'Digital Ration Card Issuance & Member Validation',
    connectionType: 'REST_API',
    status: 'ACTIVE',
    dataExchangeProtocol: 'HTTPS/JSON (e-Gov Interop v2.1)',
    dataCategories: 'Ration Card ID, Family Member Roster',
    consentRequired: true,
    totalTransactionsProcessed: 215400,
    lastTestedAt: new Date().toISOString(),
    createdAt: new Date().toISOString()
  },
  {
    id: 11,
    name: 'e-Shram to Social Welfare & Health Bridge',
    sourcePlatformId: 11,
    sourcePlatformName: 'e-Shram & EPFO National Labor Gateway',
    sourceDepartmentId: 9,
    sourceDepartmentName: 'Labour & Employment',
    destinationPlatformId: 5,
    destinationPlatformName: 'Ayushman Bharat PM-JAY National Portal',
    destinationDepartmentId: 4,
    destinationDepartmentName: 'Health & Family Welfare',
    serviceId: 28,
    serviceName: 'e-Shram National Database Unorganized Worker Smart Card',
    purpose: 'Universal Health & Insurance Entitlement Linkage',
    connectionType: 'DATA_PIPELINE',
    status: 'ACTIVE',
    dataExchangeProtocol: 'HTTPS/JSON (e-Gov Interop v2.1)',
    dataCategories: 'UAN Identifier, Occupational Code, Health Eligibility',
    consentRequired: true,
    totalTransactionsProcessed: 178900,
    lastTestedAt: new Date().toISOString(),
    createdAt: new Date().toISOString()
  },
  {
    id: 12,
    name: 'GSTN to Municipal Commercial Trade Licensing',
    sourcePlatformId: 12,
    sourcePlatformName: 'GSTN & Digital e-Stamping Interoperability Engine',
    sourceDepartmentId: 10,
    sourceDepartmentName: 'Finance & Commercial Taxes',
    destinationPlatformId: 1,
    destinationPlatformName: 'e-NagarPalika Municipal Core',
    destinationDepartmentId: 1,
    destinationDepartmentName: 'Municipal Corporation',
    serviceId: 31,
    serviceName: 'Goods & Services Tax (GST) Verification & Taxpayer Certificate',
    purpose: 'Commercial Entity Verification & Trade Clearance',
    connectionType: 'SECURE_GATEWAY',
    status: 'ACTIVE',
    dataExchangeProtocol: 'HTTPS/JSON (e-Gov Interop v2.1)',
    dataCategories: 'GSTIN Status, Legal Business Entity Name, Tax Compliance',
    consentRequired: true,
    totalTransactionsProcessed: 145200,
    lastTestedAt: new Date().toISOString(),
    createdAt: new Date().toISOString()
  },
  {
    id: 13,
    name: 'Poshan & PMMVY to DigiLocker Mother-Child Records',
    sourcePlatformId: 13,
    sourcePlatformName: 'Poshan Tracker & PMMVY Direct Benefit Platform',
    sourceDepartmentId: 11,
    sourceDepartmentName: 'Women & Child Development',
    destinationPlatformId: 6,
    destinationPlatformName: 'DigiLocker Government Document Exchange',
    destinationDepartmentId: 3,
    destinationDepartmentName: 'Inter-Department Gateway',
    serviceId: 34,
    serviceName: 'Pradhan Mantri Matru Vandana Yojana (PMMVY)',
    purpose: 'Maternal Nutrition Benefit Verification',
    connectionType: 'REST_API',
    status: 'ACTIVE',
    dataExchangeProtocol: 'HTTPS/JSON (e-Gov Interop v2.1)',
    dataCategories: 'Mother-Child Protection Card, DBT Bank Account',
    consentRequired: true,
    totalTransactionsProcessed: 98600,
    lastTestedAt: new Date().toISOString(),
    createdAt: new Date().toISOString()
  },
  {
    id: 14,
    name: 'PM Surya Ghar to DISCOM & Municipal Net Metering',
    sourcePlatformId: 14,
    sourcePlatformName: 'PM Surya Ghar National Rooftop Solar Grid Portal',
    sourceDepartmentId: 12,
    sourceDepartmentName: 'Power & Renewable Energy',
    destinationPlatformId: 1,
    destinationPlatformName: 'e-NagarPalika Municipal Core',
    destinationDepartmentId: 1,
    destinationDepartmentName: 'Municipal Corporation',
    serviceId: 37,
    serviceName: 'PM Surya Ghar: Muft Bijli Yojana Rooftop Solar Subsidy',
    purpose: 'Solar Net-Metering & Technical Feasibility Sync',
    connectionType: 'SECURE_GATEWAY',
    status: 'ACTIVE',
    dataExchangeProtocol: 'HTTPS/JSON (e-Gov Interop v2.1)',
    dataCategories: 'Electricity Consumer CA Number, Sanctioned Load, Roof Area',
    consentRequired: true,
    totalTransactionsProcessed: 87300,
    lastTestedAt: new Date().toISOString(),
    createdAt: new Date().toISOString()
  }
];

export const INITIAL_DATA_REQUIREMENTS: DataRequirement[] = [
  // Property Tax (Service 1)
  {
    id: 1,
    serviceId: 1,
    serviceName: 'Property Tax Assessment & Receipt',
    fieldName: 'Citizen Full Name',
    description: 'Legal name of the property owner as registered in UIDAI and Municipal Records',
    sourceDepartmentId: 1,
    sourceDepartmentName: 'Municipal Corporation',
    sourcePlatformId: 1,
    sourcePlatformName: 'e-NagarPalika Municipal Core',
    required: true,
    availabilityStatus: 'AVAILABLE',
    consentRequired: true,
    purpose: 'Applicant Identification'
  },
  {
    id: 2,
    serviceId: 1,
    serviceName: 'Property Tax Assessment ID',
    fieldName: 'Property Tax Assessment ID',
    description: 'Municipal property assessment record identifier and annual dues ledger',
    sourceDepartmentId: 1,
    sourceDepartmentName: 'Municipal Corporation',
    sourcePlatformId: 1,
    sourcePlatformName: 'e-NagarPalika Municipal Core',
    required: true,
    availabilityStatus: 'AVAILABLE',
    consentRequired: true,
    purpose: 'Municipal Dues Lookup'
  },
  {
    id: 3,
    serviceId: 1,
    serviceName: 'Property Tax Assessment & Receipt',
    fieldName: 'Land Ownership & Cadastral Title',
    description: 'Spatial title deed and RoR registration from Bhoomi Land Records',
    sourceDepartmentId: 3,
    sourceDepartmentName: 'Revenue & Land Records',
    sourcePlatformId: 4,
    sourcePlatformName: 'Bhoomi Land Records Information System',
    required: true,
    availabilityStatus: 'AVAILABLE',
    consentRequired: true,
    purpose: 'Title Verification'
  },
  {
    id: 4,
    serviceId: 1,
    serviceName: 'Property Tax Assessment & Receipt',
    fieldName: 'Annual Self-Assessment Declaration',
    description: 'Current occupant and construction floor status provided by citizen',
    sourceDepartmentId: 1,
    sourceDepartmentName: 'Municipal Corporation',
    sourcePlatformId: 1,
    sourcePlatformName: 'e-NagarPalika Municipal Core',
    required: false,
    availabilityStatus: 'NEEDS_INPUT',
    consentRequired: false,
    purpose: 'Assessment Calculation'
  },

  // Driving Licence (Service 4)
  {
    id: 5,
    serviceId: 4,
    serviceName: 'Driving Licence Renewal',
    fieldName: 'Citizen Identity & Photo',
    description: 'Official photo and biometric proof from national licensing database',
    sourceDepartmentId: 2,
    sourceDepartmentName: 'Transport Department',
    sourcePlatformId: 3,
    sourcePlatformName: 'SARATHI 4.0 Driving License System',
    required: true,
    availabilityStatus: 'AVAILABLE',
    consentRequired: true,
    purpose: 'Identity Matching'
  },
  {
    id: 6,
    serviceId: 4,
    serviceName: 'Driving Licence Renewal',
    fieldName: 'Existing Driving Licence Record',
    description: 'SARATHI database driving license validity and endorsement record',
    sourceDepartmentId: 2,
    sourceDepartmentName: 'Transport Department',
    sourcePlatformId: 3,
    sourcePlatformName: 'SARATHI 4.0 Driving License System',
    required: true,
    availabilityStatus: 'AVAILABLE',
    consentRequired: true,
    purpose: 'Licence Record Lookup'
  },
  {
    id: 7,
    serviceId: 4,
    serviceName: 'Driving Licence Renewal',
    fieldName: 'Medical Fitness Self-Declaration',
    description: 'Self declaration for driver fitness (Form 1A)',
    sourceDepartmentId: 4,
    sourceDepartmentName: 'Health & Family Welfare',
    sourcePlatformId: 5,
    sourcePlatformName: 'Ayushman Bharat PM-JAY National Portal',
    required: false,
    availabilityStatus: 'NEEDS_INPUT',
    consentRequired: false,
    purpose: 'Medical Suitability'
  },

  // Land Mutation (Service 7)
  {
    id: 8,
    serviceId: 7,
    serviceName: 'Land Mutation (Namantaran / Record of Rights)',
    fieldName: 'Registered Sale Deed Details',
    description: 'Sub-Registrar deed indexation number and timestamp',
    sourceDepartmentId: 3,
    sourceDepartmentName: 'Revenue & Land Records',
    sourcePlatformId: 4,
    sourcePlatformName: 'Bhoomi Land Records Information System',
    required: true,
    availabilityStatus: 'AVAILABLE',
    consentRequired: true,
    purpose: 'Deed Verification'
  },
  {
    id: 9,
    serviceId: 7,
    serviceName: 'Land Mutation (Namantaran / Record of Rights)',
    fieldName: 'Survey Number & Cadastral Boundary',
    description: 'Cadastral survey boundary records and joint ownership details',
    sourceDepartmentId: 3,
    sourceDepartmentName: 'Revenue & Land Records',
    sourcePlatformId: 4,
    sourcePlatformName: 'Bhoomi Land Records Information System',
    required: true,
    availabilityStatus: 'AVAILABLE',
    consentRequired: true,
    purpose: 'Land Boundary Verification'
  },
  {
    id: 10,
    serviceId: 7,
    serviceName: 'Land Mutation (Namantaran / Record of Rights)',
    fieldName: 'Municipal NOC Clearance',
    description: 'No-dues clearance from urban local body',
    sourceDepartmentId: 1,
    sourceDepartmentName: 'Municipal Corporation',
    sourcePlatformId: 1,
    sourcePlatformName: 'e-NagarPalika Municipal Core',
    required: true,
    availabilityStatus: 'AVAILABLE',
    consentRequired: true,
    purpose: 'Encumbrance Check'
  }
];

export const INITIAL_DATA_CONSENTS: DataConsent[] = [
  {
    id: 1,
    userId: 1,
    userName: 'Aarav Sharma',
    serviceId: 1,
    serviceName: 'Property Tax Assessment & Receipt',
    dataRequirementId: 2,
    fieldName: 'Property Tax Assessment ID',
    sourceDepartmentName: 'Municipal Corporation',
    sourcePlatformName: 'e-NagarPalika Municipal Core',
    purpose: 'Municipal Dues Lookup',
    status: 'ACTIVE',
    grantedAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString()
  },
  {
    id: 2,
    userId: 1,
    userName: 'Aarav Sharma',
    serviceId: 1,
    serviceName: 'Property Tax Assessment & Receipt',
    dataRequirementId: 3,
    fieldName: 'Land Ownership & Cadastral Title',
    sourceDepartmentName: 'Revenue & Land Records',
    sourcePlatformName: 'Bhoomi Land Records Information System',
    purpose: 'Title Verification',
    status: 'ACTIVE',
    grantedAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString()
  },
  {
    id: 3,
    userId: 1,
    userName: 'Aarav Sharma',
    serviceId: 4,
    serviceName: 'Driving Licence Renewal',
    dataRequirementId: 6,
    fieldName: 'Existing Driving Licence Record',
    sourceDepartmentName: 'Transport Department',
    sourcePlatformName: 'SARATHI 4.0 Driving License System',
    purpose: 'Licence Renewal',
    status: 'ACTIVE',
    grantedAt: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString()
  },
  {
    id: 4,
    userId: 1,
    userName: 'Aarav Sharma',
    serviceId: 10,
    serviceName: 'Ayushman Bharat PM-JAY Golden Card',
    fieldName: 'Aadhaar Health Beneficiary Match',
    sourceDepartmentName: 'Health & Family Welfare',
    sourcePlatformName: 'Ayushman Bharat PM-JAY National Portal',
    purpose: 'Golden Card Issuance',
    status: 'ACTIVE',
    grantedAt: new Date(Date.now() - 14 * 24 * 60 * 60 * 1000).toISOString()
  }
];

export const INITIAL_WORKFLOWS: ServiceWorkflow[] = [
  {
    id: 1,
    serviceId: 1,
    serviceName: 'Property Tax Assessment & Receipt',
    name: 'Municipal Property Tax End-to-End Workflow',
    description: 'Automated land registry query, municipal dues computation, officer scrutiny, and digital receipt delivery.',
    status: 'ACTIVE',
    totalSteps: 5,
    createdAt: new Date().toISOString()
  },
  {
    id: 2,
    serviceId: 4,
    serviceName: 'Driving Licence Renewal',
    name: 'Contactless Driving Licence Renewal Workflow',
    description: 'SARATHI biometric lookup, RTO zonal authorization, smart card dispatch.',
    status: 'ACTIVE',
    totalSteps: 4,
    createdAt: new Date().toISOString()
  }
];

export const INITIAL_WORKFLOW_STEPS: WorkflowStep[] = [
  // Workflow 1 (Property Tax)
  {
    id: 1,
    workflowId: 1,
    stepName: 'Application Received & Queued',
    stepOrder: 1,
    departmentId: 1,
    departmentName: 'Municipal Corporation',
    platformId: 1,
    platformName: 'e-NagarPalika Municipal Core',
    citizenDescription: 'Your request is registered on the SAMAVAY network with an instant tracking identifier.',
    status: 'COMPLETED'
  },
  {
    id: 2,
    workflowId: 1,
    stepName: 'Land Records Interoperability Lookup',
    stepOrder: 2,
    departmentId: 3,
    departmentName: 'Revenue & Land Records',
    platformId: 4,
    platformName: 'Bhoomi Land Records Information System',
    citizenDescription: 'Title and survey plot records are being cross-verified with the Bhoomi Land Records registry.',
    status: 'COMPLETED'
  },
  {
    id: 3,
    workflowId: 1,
    stepName: 'Municipal Tax Officer Assessment',
    stepOrder: 3,
    departmentId: 1,
    departmentName: 'Municipal Corporation',
    platformId: 1,
    platformName: 'e-NagarPalika Municipal Core',
    citizenDescription: 'Municipal Revenue Inspector is reviewing the verified plot details and self-declared assessment.',
    status: 'IN_PROGRESS'
  },
  {
    id: 4,
    workflowId: 1,
    stepName: 'Digital Seal & Clearance',
    stepOrder: 4,
    departmentId: 1,
    departmentName: 'Municipal Corporation',
    platformId: 1,
    platformName: 'e-NagarPalika Municipal Core',
    citizenDescription: 'Digital certificate and tax receipt are queued for sovereign PKI digital signing.',
    status: 'ACTIVE'
  },
  {
    id: 5,
    workflowId: 1,
    stepName: 'Digital Delivery to Citizen & DigiLocker',
    stepOrder: 5,
    departmentId: 3,
    departmentName: 'Inter-Department Gateway',
    platformId: 6,
    platformName: 'DigiLocker Government Document Exchange',
    citizenDescription: 'Final digitally verifiable receipt is issued to your portal dashboard and synced with DigiLocker.',
    status: 'ACTIVE'
  },

  // Workflow 2 (Driving Licence)
  {
    id: 6,
    workflowId: 2,
    stepName: 'Renewal Request Submitted',
    stepOrder: 1,
    departmentId: 2,
    departmentName: 'Transport Department',
    platformId: 3,
    platformName: 'SARATHI 4.0 Driving License System',
    citizenDescription: 'Renewal application received and mapped to your RTO North Zone.',
    status: 'COMPLETED'
  },
  {
    id: 7,
    workflowId: 2,
    stepName: 'Biometric & Medical Verification',
    stepOrder: 2,
    departmentId: 2,
    departmentName: 'Transport Department',
    platformId: 3,
    platformName: 'SARATHI 4.0 Driving License System',
    citizenDescription: 'Biometric record matched against national SARATHI central database.',
    status: 'COMPLETED'
  },
  {
    id: 8,
    workflowId: 2,
    stepName: 'RTO Officer Approval',
    stepOrder: 3,
    departmentId: 2,
    departmentName: 'Transport Department',
    platformId: 3,
    platformName: 'SARATHI 4.0 Driving License System',
    citizenDescription: 'Licensing Authority has approved your renewed validity period.',
    status: 'COMPLETED'
  },
  {
    id: 9,
    workflowId: 2,
    stepName: 'Digital Certificate & Smart Card Dispatched',
    stepOrder: 4,
    departmentId: 2,
    departmentName: 'Transport Department',
    platformId: 6,
    platformName: 'DigiLocker Government Document Exchange',
    citizenDescription: 'Digital renewal slip issued to DigiLocker and physical smart card dispatched via India Post.',
    status: 'COMPLETED'
  }
];

export const INITIAL_AUDIT_LOGS: AuditLog[] = [
  {
    id: 1,
    userId: 1,
    action: 'CONSENT_GRANTED',
    performedBy: 'Aarav Sharma (Citizen)',
    resourceType: 'DataConsent',
    resourceId: 1,
    description: 'Citizen authorized Property Tax service to access Land Records System under DPDP compliant token.',
    details: 'Scope: Property Deed Lookup, Title Verification',
    ipAddress: '192.168.1.45',
    timestamp: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString()
  },
  {
    id: 2,
    userId: 2,
    action: 'INTEGRATION_PIPELINE_ACTIVE',
    performedBy: 'Rajesh Varma (Officer)',
    resourceType: 'IntegrationConnection',
    resourceId: 1,
    description: 'Municipal-to-Land Records secure data exchange pipeline verified with 142k transactions processed.',
    details: 'Latency: 38ms, Protocol: HTTPS/JSON e-Gov v2.1',
    ipAddress: '10.0.4.12',
    timestamp: new Date(Date.now() - 6 * 60 * 60 * 1000).toISOString()
  },
  {
    id: 3,
    userId: 3,
    action: 'PLATFORM_REGISTERED',
    performedBy: 'Suresh Patel (Super Admin)',
    resourceType: 'GovernmentPlatform',
    resourceId: 7,
    description: 'Registered new national platform: National Scholarship & PFMS Portal (PFMS-NSP).',
    details: 'Environment: PRODUCTION, Auth: PKI_X509',
    ipAddress: '10.0.1.2',
    timestamp: new Date(Date.now() - 24 * 60 * 60 * 1000).toISOString()
  },
  {
    id: 4,
    userId: 1,
    action: 'SERVICE_REQUEST_SUBMITTED',
    performedBy: 'Aarav Sharma (Citizen)',
    resourceType: 'ServiceRequest',
    resourceId: 1,
    description: 'Submitted application #SAM-2026-10234 for Property Tax Assessment with pre-filled Land Title.',
    details: 'Reused verified record from Bhoomi LRS',
    ipAddress: '192.168.1.45',
    timestamp: new Date(Date.now() - 48 * 60 * 60 * 1000).toISOString()
  }
];

export const INITIAL_REQUESTS: ServiceRequest[] = [
  {
    id: 1,
    applicationNumber: 'SAM-2026-10234',
    userId: 1,
    applicantName: 'Aarav Sharma',
    applicantEmail: 'citizen.demo@samavay.gov.in',
    applicantPhone: '9876543210',
    serviceId: 1,
    serviceName: 'Property Tax Assessment & Receipt',
    departmentName: 'Municipal Corporation',
    category: 'MUNICIPAL',
    formDataJson: JSON.stringify({
      propertyId: 'M-WARD-40982',
      ownerName: 'Aarav Sharma',
      address: 'Sector 4, Green Park',
      assessmentYear: '2026-2027'
    }),
    status: 'PROCESSING',
    currentStage: 'Municipal Tax Officer Assessment & Verification',
    remarks: 'Land registry data matched automatically via Bhoomi Interop pipe. Final assessment in signing queue.',
    submittedAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString()
  },
  {
    id: 2,
    applicationNumber: 'SAM-2026-09841',
    userId: 1,
    applicantName: 'Aarav Sharma',
    applicantEmail: 'citizen.demo@samavay.gov.in',
    applicantPhone: '9876543210',
    serviceId: 4,
    serviceName: 'Driving Licence Renewal',
    departmentName: 'Transport Department',
    category: 'TRANSPORT',
    formDataJson: JSON.stringify({
      currentDlNumber: 'DL-1420110023412',
      rtoZone: 'North Zone RTO 01',
      bloodGroup: 'B+'
    }),
    status: 'COMPLETED',
    currentStage: 'Smart Card Dispatched & Digital RC Generated',
    remarks: 'Biometric matched successfully via Sarathi Interop Gateway. Digital certificate issued.',
    certificateUrl: 'https://samavay.gov.in/certs/DL-SAM-2026-09841.pdf',
    submittedAt: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString()
  },
  {
    id: 3,
    applicationNumber: 'SAM-2026-11490',
    userId: 1,
    applicantName: 'Aarav Sharma',
    applicantEmail: 'citizen.demo@samavay.gov.in',
    applicantPhone: '9876543210',
    serviceId: 8,
    serviceName: 'Income & Asset Certificate',
    departmentName: 'Revenue & Land Records',
    category: 'REVENUE',
    formDataJson: JSON.stringify({
      annualIncome: '420000',
      purpose: 'Higher Education Scholarship',
      taluk: 'Central Taluk'
    }),
    status: 'UNDER_REVIEW',
    currentStage: 'Revenue Inspector Field Inquiry',
    remarks: 'Application assigned to Circle Inspector. Verification scheduled.',
    submittedAt: new Date(Date.now() - 18 * 60 * 60 * 1000).toISOString()
  }
];

export const INITIAL_NOTIFICATIONS: NotificationItem[] = [
  {
    id: 1,
    userId: 1,
    title: 'Driving Licence Renewed Successfully',
    message: 'Your Driving Licence renewal application #SAM-2026-09841 is completed. Digital certificate is available for download.',
    type: 'SUCCESS',
    actionLink: '/applications',
    isRead: false,
    createdAt: new Date(Date.now() - 4 * 60 * 60 * 1000).toISOString()
  },
  {
    id: 2,
    userId: 1,
    title: 'Property Tax Assessment in Progress',
    message: 'Application #SAM-2026-10234: Land records verified via Bhoomi Interop pipeline. Assigned to municipal scrutiny officer.',
    type: 'INFO',
    actionLink: '/applications',
    isRead: false,
    createdAt: new Date(Date.now() - 24 * 60 * 60 * 1000).toISOString()
  },
  {
    id: 3,
    userId: 1,
    title: 'Data Permission Active',
    message: 'Consent active for Property Tax Assessment to access Land Records and Municipal Dues.',
    type: 'UPDATE',
    actionLink: '/dashboard/permissions',
    isRead: true,
    createdAt: new Date(Date.now() - 36 * 60 * 60 * 1000).toISOString()
  }
];
